FROM ubuntu:18.04

# Mudanças menos frequentes devem ficar no topo - "leverage caching"
RUN apt-get update \
&& apt-get upgrade -y \
&& apt-get install -y nodejs npm \
&& rm -rf /var/lib/apt/lists/* 

# Preferir COPY do que ADD
COPY . .
RUN npm install

EXPOSE 8080
CMD ["node", "hello.js"]

